// SOAL
/*
BUATLAH SEBUAH PROGRAM UNTUK MELIHAT APAKAH PELAMAR MEMENUHI KUALIFIKASI UNTUK BEKERJA DI PERUSAHAAN JAMBRUT
1. SYARAT MINIMAL HARUS BERUMUR 18 TAHUN
2. HARUS BERASAL DARI KOTA 'GOTHAM'
3. ADA JOBDESK YANG DILAMAR 'ENGINEER' DAN 'HRD'
4. UMUR YANG 32 TAHUN KEATAS AKAN PRINT 'SELAMAT KAMU DITERIMA DI JAMBRUT DIVISI SENIOR SEBAGAI <JOBDESKNYA>'
5. UMUR YANG DIBAWAH 32 TAHUN AKAN PRINT 'SELAMAT KAMU DITERIMA DI JAMBRUT DIVISI JUNIOR SEBAGAI <JOBDESKNYA>'
6. JOBDESK HRD HANYA MENERIMA DIVISI SENIOR
*/